api_version = "2026-04"

[[extensions]]
name = "t:name"
handle = "quantity-breaks-discount"
type = "function"
uid = "8b5d80e7-60a9-c650-e8d0-0a71b02b18001268297b"
description = "t:description"

  [[extensions.targeting]]
  target = "purchase.product-discount.run"
  input_query = "src/run.graphql"
  export = "run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/"
  details = "/"
