# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "57d42e91a1465332c85a51b24dd81cda"
name = "Bundley"
application_url = "https://bundley.onrender.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products,read_discounts,write_discounts"

[webhooks]
api_version = "2026-07"

  [webhooks.privacy_compliance]
  customer_data_request_url = "/webhooks/customers/data_request"
  customer_deletion_url = "/webhooks/customers/redact"
  shop_deletion_url = "/webhooks/shop/redact"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

[auth]
redirect_urls = [ "https://bundley.onrender.com/auth/callback" ]

[build]
automatically_update_urls_on_dev = true
